name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # DOCKER_REGISTRY: docker.io
      # DOCKER_IMAGE: ashish21bd/c-arm64v8
      # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # DOCKER_TARGET_PLATFORM: linux/arm/v8
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Docker build and push
      uses: azure/docker-login@v1
      with:
          login-server: vehilcle.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
          docker build . -t vehilcle.azurecr.io/vehicle-app:${{ github.sha }}
          docker push testcppapp.azurecr.io/vehicle-app:${{ github.sha }}