name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # DOCKER_REGISTRY: docker.io
      # DOCKER_IMAGE: ashish21bd/c-arm64v8
      # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # DOCKER_TARGET_PLATFORM: linux/arm/v8
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Docker build and push
      uses: azure/docker-login@v1
      with:
          login-server: vehicleacrscn.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
           docker build . --platform linux/arm64v8 -t vehicleacrscn.azurecr.io/obdsignalgen:${{ github.run_number }}
           docker push vehicleacrscn.azurecr.io/obdsignalgen:${{ github.run_number }}
#          docker build . -t vehicleacrscn.azurecr.io/obdsignalgen:${{ github.sha }}
#          docker push vehicleacrscn.azurecr.io/obdsignalgen:${{ github.sha }}
