name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # DOCKER_REGISTRY: docker.io
      # DOCKER_IMAGE: ashish21bd/c-arm64v8
      # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # DOCKER_TARGET_PLATFORM: linux/arm/v8
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

#SonarCloud Scanner
    - name: Install sonar-scanner and build-wrapper
      uses: SonarSource/sonarcloud-github-c-cpp@v1

#Running Build wrapper for C
    - name: Run build-wrapper
      run: |
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} gcc -o myapp create_json.cpp
