name: Release Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.13.0
        with:
          push: true
          # Use a unique tag (for example, the commit SHA)
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/release_c-app:${{ github.sha }}

      # Set the short SHA for a prettier version tag.
      - name: Set short SHA
        id: get_sha
        run: echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Create GitHub release with Docker image version
        id: create_release
        uses: ncipollo/release-action@v1.15.0
        with:
          tag: v${{ steps.get_sha.outputs.short_sha }}
          name: "Release v${{ steps.get_sha.outputs.short_sha }}"
          body: |
            Docker image [your-dockerhub-username/release_c-app:v${{ steps.get_sha.outputs.short_sha }}](https://hub.docker.com/r/your-dockerhub-username/release_c-app/tags)
            has been built and pushed.


